gtd:
  learning_rate: 0.001
  epochs: 1
  chunk_size: 512
  chunk_overlap: 64
  weights_path: "output/gtd"
  weights_filename: "model_weights-epochs(1)_chunk_size(512)_chunk_overlap(64).h5"
  train_data_path: "data/subtask_A/subtaskA_train_monolingual.jsonl"
  test_data_path: "data/subtask_A/subtaskA_dev_monolingual.jsonl"

lmd:
  learning_rate: 0.001
  epochs: 1
  chunk_size: 512
  chunk_overlap: 64
  weights_path: "output/lmd"
  weights_filename: ""
  train_data_path: "data/subtask_B/subtaskB_train.jsonl"
  test_data_path: "data/subtask_B/subtaskB_dev.jsonl"

tsd:
  learning_rate: 0.001
  epochs: 1
  chunk_size: 512
  chunk_overlap: 64
  weights_path: "output/tsd"
  weights_filename: ""
  train_data_path: "data/subtask_C/subtaskC_train.jsonl"
  test_data_path: "data/subtask_C/subtaskC_dev.jsonl"